version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - node.name=docker-node
      - cluster.name=docker-cluster
      - http.host=0.0.0.0
      - http.port=9200
      - http.cors.allow-origin=http://localhost:3000
      - http.cors.enabled=true
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization,Accept,Origin,Access-Control-Allow-Headers,x-elastic-client-meta
      - http.cors.allow-credentials=true
      - http.cors.allow-methods=OPTIONS,HEAD,GET,POST,PUT,DELETE
    networks:
      docker-elk:
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.0
    container_name: kibana
    environment:
      - "ELASTICSEARCH_URL=http://localhost:9200"
    networks:
      - docker-elk
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

networks:
  docker-elk:
    driver: bridge
